# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Justin Carter
description:      Some Fun Stuff
url:              http://justinrc.com
github_username:  bodymindarts
twitter_username: bodymindarts
